# Generated by Django 3.2.5 on 2021-07-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='User',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
